name: Windows browser render

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'dev' or 'stable'

    - run: flutter pub get
    - run: flutter build web
    - run: flutter test test/puppeteer.dart

    - uses: actions/upload-artifact@v2
      with:
        name: Screenshot
        path: chrome.png
